baseURL = "https://santifu.github.io/web/"
title   = "Santi Fuentemilla"

defaultContentLanguage        = "es"
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    languageName = "Español"
    weight       = 1
    contentDir   = "content/es"
  [languages.ca]
    languageName = "Català"
    weight       = 2
    contentDir   = "content/ca"
  [languages.en]
    languageName = "English"
    weight       = 3
    contentDir   = "content/en"

[params]
  email    = "santi@fablabbcn.org"
  github   = "https://github.com/santifu"
  linkedin = "https://linkedin.com/in/yourusername"
  org      = "Fab Lab Barcelona / IAAC"
  ogImage  = "/img/og.jpg"
